// Lista curada de versículos com profundidade devocional e visão reformada.
// Fonte: Salmos, Profetas (Isaías, Jeremias, Habacuque), Samuel, Gênesis e NT completo.
// O nome do livro deve corresponder exatamente ao cadastrado no banco (versão ARC).

export type VerseRef = { book: string; chapter: number; verse: number };

export const CURATED_VERSES: VerseRef[] = [
  // ── GÊNESIS ──────────────────────────────────────────────────────────────────
  { book: 'Gênesis', chapter: 1, verse: 1 },
  { book: 'Gênesis', chapter: 1, verse: 27 },
  { book: 'Gênesis', chapter: 1, verse: 31 },
  { book: 'Gênesis', chapter: 2, verse: 7 },
  { book: 'Gênesis', chapter: 2, verse: 18 },
  { book: 'Gênesis', chapter: 3, verse: 15 },
  { book: 'Gênesis', chapter: 12, verse: 1 },
  { book: 'Gênesis', chapter: 15, verse: 6 },
  { book: 'Gênesis', chapter: 17, verse: 1 },
  { book: 'Gênesis', chapter: 18, verse: 14 },
  { book: 'Gênesis', chapter: 22, verse: 8 },
  { book: 'Gênesis', chapter: 22, verse: 14 },
  { book: 'Gênesis', chapter: 28, verse: 15 },
  { book: 'Gênesis', chapter: 50, verse: 20 },

  // ── 1 SAMUEL ─────────────────────────────────────────────────────────────────
  { book: '1 Samuel', chapter: 2, verse: 2 },
  { book: '1 Samuel', chapter: 2, verse: 6 },
  { book: '1 Samuel', chapter: 2, verse: 7 },
  { book: '1 Samuel', chapter: 2, verse: 9 },
  { book: '1 Samuel', chapter: 3, verse: 19 },
  { book: '1 Samuel', chapter: 7, verse: 12 },
  { book: '1 Samuel', chapter: 12, verse: 24 },
  { book: '1 Samuel', chapter: 15, verse: 22 },
  { book: '1 Samuel', chapter: 16, verse: 7 },
  { book: '1 Samuel', chapter: 17, verse: 47 },

  // ── 2 SAMUEL ─────────────────────────────────────────────────────────────────
  { book: '2 Samuel', chapter: 7, verse: 22 },
  { book: '2 Samuel', chapter: 7, verse: 28 },
  { book: '2 Samuel', chapter: 22, verse: 3 },
  { book: '2 Samuel', chapter: 22, verse: 31 },
  { book: '2 Samuel', chapter: 22, verse: 47 },
  { book: '2 Samuel', chapter: 23, verse: 5 },

  // ── SALMOS ───────────────────────────────────────────────────────────────────
  { book: 'Salmos', chapter: 1, verse: 1 },
  { book: 'Salmos', chapter: 1, verse: 3 },
  { book: 'Salmos', chapter: 2, verse: 7 },
  { book: 'Salmos', chapter: 8, verse: 1 },
  { book: 'Salmos', chapter: 16, verse: 2 },
  { book: 'Salmos', chapter: 16, verse: 11 },
  { book: 'Salmos', chapter: 19, verse: 1 },
  { book: 'Salmos', chapter: 19, verse: 7 },
  { book: 'Salmos', chapter: 19, verse: 14 },
  { book: 'Salmos', chapter: 22, verse: 1 },
  { book: 'Salmos', chapter: 23, verse: 1 },
  { book: 'Salmos', chapter: 23, verse: 4 },
  { book: 'Salmos', chapter: 23, verse: 6 },
  { book: 'Salmos', chapter: 27, verse: 1 },
  { book: 'Salmos', chapter: 27, verse: 4 },
  { book: 'Salmos', chapter: 31, verse: 15 },
  { book: 'Salmos', chapter: 32, verse: 1 },
  { book: 'Salmos', chapter: 33, verse: 6 },
  { book: 'Salmos', chapter: 33, verse: 11 },
  { book: 'Salmos', chapter: 34, verse: 8 },
  { book: 'Salmos', chapter: 37, verse: 4 },
  { book: 'Salmos', chapter: 37, verse: 23 },
  { book: 'Salmos', chapter: 40, verse: 8 },
  { book: 'Salmos', chapter: 42, verse: 1 },
  { book: 'Salmos', chapter: 46, verse: 1 },
  { book: 'Salmos', chapter: 46, verse: 10 },
  { book: 'Salmos', chapter: 51, verse: 1 },
  { book: 'Salmos', chapter: 51, verse: 10 },
  { book: 'Salmos', chapter: 51, verse: 17 },
  { book: 'Salmos', chapter: 55, verse: 22 },
  { book: 'Salmos', chapter: 62, verse: 1 },
  { book: 'Salmos', chapter: 63, verse: 1 },
  { book: 'Salmos', chapter: 63, verse: 3 },
  { book: 'Salmos', chapter: 65, verse: 4 },
  { book: 'Salmos', chapter: 73, verse: 25 },
  { book: 'Salmos', chapter: 73, verse: 28 },
  { book: 'Salmos', chapter: 84, verse: 1 },
  { book: 'Salmos', chapter: 84, verse: 10 },
  { book: 'Salmos', chapter: 84, verse: 11 },
  { book: 'Salmos', chapter: 86, verse: 5 },
  { book: 'Salmos', chapter: 90, verse: 1 },
  { book: 'Salmos', chapter: 90, verse: 2 },
  { book: 'Salmos', chapter: 91, verse: 1 },
  { book: 'Salmos', chapter: 91, verse: 4 },
  { book: 'Salmos', chapter: 93, verse: 1 },
  { book: 'Salmos', chapter: 100, verse: 3 },
  { book: 'Salmos', chapter: 100, verse: 5 },
  { book: 'Salmos', chapter: 103, verse: 8 },
  { book: 'Salmos', chapter: 103, verse: 12 },
  { book: 'Salmos', chapter: 103, verse: 17 },
  { book: 'Salmos', chapter: 104, verse: 24 },
  { book: 'Salmos', chapter: 107, verse: 1 },
  { book: 'Salmos', chapter: 110, verse: 1 },
  { book: 'Salmos', chapter: 111, verse: 10 },
  { book: 'Salmos', chapter: 115, verse: 1 },
  { book: 'Salmos', chapter: 116, verse: 1 },
  { book: 'Salmos', chapter: 118, verse: 22 },
  { book: 'Salmos', chapter: 119, verse: 9 },
  { book: 'Salmos', chapter: 119, verse: 11 },
  { book: 'Salmos', chapter: 119, verse: 105 },
  { book: 'Salmos', chapter: 119, verse: 130 },
  { book: 'Salmos', chapter: 121, verse: 1 },
  { book: 'Salmos', chapter: 121, verse: 8 },
  { book: 'Salmos', chapter: 127, verse: 1 },
  { book: 'Salmos', chapter: 130, verse: 3 },
  { book: 'Salmos', chapter: 139, verse: 1 },
  { book: 'Salmos', chapter: 139, verse: 7 },
  { book: 'Salmos', chapter: 139, verse: 13 },
  { book: 'Salmos', chapter: 143, verse: 10 },
  { book: 'Salmos', chapter: 145, verse: 3 },
  { book: 'Salmos', chapter: 145, verse: 9 },
  { book: 'Salmos', chapter: 147, verse: 5 },
  { book: 'Salmos', chapter: 150, verse: 6 },

  // ── ISAÍAS ───────────────────────────────────────────────────────────────────
  { book: 'Isaías', chapter: 1, verse: 18 },
  { book: 'Isaías', chapter: 6, verse: 3 },
  { book: 'Isaías', chapter: 6, verse: 8 },
  { book: 'Isaías', chapter: 7, verse: 14 },
  { book: 'Isaías', chapter: 9, verse: 6 },
  { book: 'Isaías', chapter: 25, verse: 1 },
  { book: 'Isaías', chapter: 26, verse: 3 },
  { book: 'Isaías', chapter: 26, verse: 4 },
  { book: 'Isaías', chapter: 40, verse: 8 },
  { book: 'Isaías', chapter: 40, verse: 11 },
  { book: 'Isaías', chapter: 40, verse: 28 },
  { book: 'Isaías', chapter: 40, verse: 29 },
  { book: 'Isaías', chapter: 40, verse: 31 },
  { book: 'Isaías', chapter: 41, verse: 10 },
  { book: 'Isaías', chapter: 41, verse: 13 },
  { book: 'Isaías', chapter: 43, verse: 1 },
  { book: 'Isaías', chapter: 43, verse: 2 },
  { book: 'Isaías', chapter: 43, verse: 25 },
  { book: 'Isaías', chapter: 44, verse: 6 },
  { book: 'Isaías', chapter: 45, verse: 5 },
  { book: 'Isaías', chapter: 45, verse: 22 },
  { book: 'Isaías', chapter: 46, verse: 10 },
  { book: 'Isaías', chapter: 48, verse: 11 },
  { book: 'Isaías', chapter: 49, verse: 16 },
  { book: 'Isaías', chapter: 53, verse: 3 },
  { book: 'Isaías', chapter: 53, verse: 4 },
  { book: 'Isaías', chapter: 53, verse: 5 },
  { book: 'Isaías', chapter: 53, verse: 6 },
  { book: 'Isaías', chapter: 53, verse: 11 },
  { book: 'Isaías', chapter: 54, verse: 10 },
  { book: 'Isaías', chapter: 55, verse: 6 },
  { book: 'Isaías', chapter: 55, verse: 7 },
  { book: 'Isaías', chapter: 55, verse: 8 },
  { book: 'Isaías', chapter: 55, verse: 11 },
  { book: 'Isaías', chapter: 57, verse: 15 },
  { book: 'Isaías', chapter: 61, verse: 1 },
  { book: 'Isaías', chapter: 61, verse: 10 },
  { book: 'Isaías', chapter: 64, verse: 6 },
  { book: 'Isaías', chapter: 66, verse: 2 },

  // ── JEREMIAS ─────────────────────────────────────────────────────────────────
  { book: 'Jeremias', chapter: 1, verse: 5 },
  { book: 'Jeremias', chapter: 9, verse: 23 },
  { book: 'Jeremias', chapter: 10, verse: 6 },
  { book: 'Jeremias', chapter: 10, verse: 10 },
  { book: 'Jeremias', chapter: 17, verse: 7 },
  { book: 'Jeremias', chapter: 17, verse: 9 },
  { book: 'Jeremias', chapter: 17, verse: 14 },
  { book: 'Jeremias', chapter: 23, verse: 6 },
  { book: 'Jeremias', chapter: 29, verse: 11 },
  { book: 'Jeremias', chapter: 29, verse: 13 },
  { book: 'Jeremias', chapter: 31, verse: 3 },
  { book: 'Jeremias', chapter: 31, verse: 33 },
  { book: 'Jeremias', chapter: 31, verse: 34 },
  { book: 'Jeremias', chapter: 32, verse: 17 },
  { book: 'Jeremias', chapter: 32, verse: 27 },
  { book: 'Jeremias', chapter: 33, verse: 3 },

  // ── HABACUQUE ────────────────────────────────────────────────────────────────
  { book: 'Habacuque', chapter: 1, verse: 12 },
  { book: 'Habacuque', chapter: 2, verse: 4 },
  { book: 'Habacuque', chapter: 2, verse: 14 },
  { book: 'Habacuque', chapter: 2, verse: 20 },
  { book: 'Habacuque', chapter: 3, verse: 18 },
  { book: 'Habacuque', chapter: 3, verse: 19 },

  // ── MATEUS ───────────────────────────────────────────────────────────────────
  { book: 'Mateus', chapter: 4, verse: 4 },
  { book: 'Mateus', chapter: 5, verse: 3 },
  { book: 'Mateus', chapter: 5, verse: 6 },
  { book: 'Mateus', chapter: 5, verse: 8 },
  { book: 'Mateus', chapter: 5, verse: 14 },
  { book: 'Mateus', chapter: 5, verse: 16 },
  { book: 'Mateus', chapter: 6, verse: 9 },
  { book: 'Mateus', chapter: 6, verse: 33 },
  { book: 'Mateus', chapter: 7, verse: 7 },
  { book: 'Mateus', chapter: 11, verse: 28 },
  { book: 'Mateus', chapter: 11, verse: 29 },
  { book: 'Mateus', chapter: 16, verse: 18 },
  { book: 'Mateus', chapter: 16, verse: 24 },
  { book: 'Mateus', chapter: 16, verse: 26 },
  { book: 'Mateus', chapter: 18, verse: 20 },
  { book: 'Mateus', chapter: 19, verse: 26 },
  { book: 'Mateus', chapter: 22, verse: 37 },
  { book: 'Mateus', chapter: 24, verse: 35 },
  { book: 'Mateus', chapter: 28, verse: 18 },
  { book: 'Mateus', chapter: 28, verse: 19 },
  { book: 'Mateus', chapter: 28, verse: 20 },

  // ── MARCOS ───────────────────────────────────────────────────────────────────
  { book: 'Marcos', chapter: 1, verse: 15 },
  { book: 'Marcos', chapter: 8, verse: 34 },
  { book: 'Marcos', chapter: 9, verse: 23 },
  { book: 'Marcos', chapter: 10, verse: 45 },
  { book: 'Marcos', chapter: 16, verse: 15 },

  // ── LUCAS ────────────────────────────────────────────────────────────────────
  { book: 'Lucas', chapter: 1, verse: 37 },
  { book: 'Lucas', chapter: 2, verse: 11 },
  { book: 'Lucas', chapter: 4, verse: 18 },
  { book: 'Lucas', chapter: 9, verse: 23 },
  { book: 'Lucas', chapter: 12, verse: 32 },
  { book: 'Lucas', chapter: 15, verse: 7 },
  { book: 'Lucas', chapter: 15, verse: 20 },
  { book: 'Lucas', chapter: 19, verse: 10 },
  { book: 'Lucas', chapter: 23, verse: 34 },
  { book: 'Lucas', chapter: 24, verse: 46 },

  // ── JOÃO ─────────────────────────────────────────────────────────────────────
  { book: 'João', chapter: 1, verse: 1 },
  { book: 'João', chapter: 1, verse: 3 },
  { book: 'João', chapter: 1, verse: 12 },
  { book: 'João', chapter: 1, verse: 14 },
  { book: 'João', chapter: 1, verse: 17 },
  { book: 'João', chapter: 1, verse: 29 },
  { book: 'João', chapter: 3, verse: 3 },
  { book: 'João', chapter: 3, verse: 16 },
  { book: 'João', chapter: 3, verse: 17 },
  { book: 'João', chapter: 3, verse: 36 },
  { book: 'João', chapter: 4, verse: 24 },
  { book: 'João', chapter: 5, verse: 24 },
  { book: 'João', chapter: 6, verse: 37 },
  { book: 'João', chapter: 6, verse: 39 },
  { book: 'João', chapter: 6, verse: 44 },
  { book: 'João', chapter: 6, verse: 47 },
  { book: 'João', chapter: 8, verse: 12 },
  { book: 'João', chapter: 8, verse: 32 },
  { book: 'João', chapter: 8, verse: 36 },
  { book: 'João', chapter: 10, verse: 10 },
  { book: 'João', chapter: 10, verse: 11 },
  { book: 'João', chapter: 10, verse: 27 },
  { book: 'João', chapter: 10, verse: 28 },
  { book: 'João', chapter: 10, verse: 29 },
  { book: 'João', chapter: 11, verse: 25 },
  { book: 'João', chapter: 13, verse: 34 },
  { book: 'João', chapter: 14, verse: 1 },
  { book: 'João', chapter: 14, verse: 6 },
  { book: 'João', chapter: 14, verse: 13 },
  { book: 'João', chapter: 14, verse: 15 },
  { book: 'João', chapter: 14, verse: 26 },
  { book: 'João', chapter: 15, verse: 4 },
  { book: 'João', chapter: 15, verse: 5 },
  { book: 'João', chapter: 15, verse: 7 },
  { book: 'João', chapter: 15, verse: 13 },
  { book: 'João', chapter: 15, verse: 16 },
  { book: 'João', chapter: 16, verse: 13 },
  { book: 'João', chapter: 16, verse: 33 },
  { book: 'João', chapter: 17, verse: 3 },
  { book: 'João', chapter: 17, verse: 17 },
  { book: 'João', chapter: 20, verse: 31 },

  // ── ATOS ─────────────────────────────────────────────────────────────────────
  { book: 'Atos', chapter: 1, verse: 8 },
  { book: 'Atos', chapter: 2, verse: 38 },
  { book: 'Atos', chapter: 2, verse: 42 },
  { book: 'Atos', chapter: 4, verse: 12 },
  { book: 'Atos', chapter: 17, verse: 24 },
  { book: 'Atos', chapter: 17, verse: 28 },
  { book: 'Atos', chapter: 20, verse: 28 },

  // ── ROMANOS ──────────────────────────────────────────────────────────────────
  { book: 'Romanos', chapter: 1, verse: 16 },
  { book: 'Romanos', chapter: 1, verse: 17 },
  { book: 'Romanos', chapter: 3, verse: 23 },
  { book: 'Romanos', chapter: 3, verse: 24 },
  { book: 'Romanos', chapter: 4, verse: 5 },
  { book: 'Romanos', chapter: 5, verse: 1 },
  { book: 'Romanos', chapter: 5, verse: 5 },
  { book: 'Romanos', chapter: 5, verse: 8 },
  { book: 'Romanos', chapter: 5, verse: 17 },
  { book: 'Romanos', chapter: 6, verse: 4 },
  { book: 'Romanos', chapter: 6, verse: 23 },
  { book: 'Romanos', chapter: 8, verse: 1 },
  { book: 'Romanos', chapter: 8, verse: 14 },
  { book: 'Romanos', chapter: 8, verse: 16 },
  { book: 'Romanos', chapter: 8, verse: 17 },
  { book: 'Romanos', chapter: 8, verse: 18 },
  { book: 'Romanos', chapter: 8, verse: 28 },
  { book: 'Romanos', chapter: 8, verse: 29 },
  { book: 'Romanos', chapter: 8, verse: 30 },
  { book: 'Romanos', chapter: 8, verse: 31 },
  { book: 'Romanos', chapter: 8, verse: 32 },
  { book: 'Romanos', chapter: 8, verse: 37 },
  { book: 'Romanos', chapter: 8, verse: 38 },
  { book: 'Romanos', chapter: 9, verse: 16 },
  { book: 'Romanos', chapter: 10, verse: 9 },
  { book: 'Romanos', chapter: 10, verse: 13 },
  { book: 'Romanos', chapter: 10, verse: 17 },
  { book: 'Romanos', chapter: 11, verse: 33 },
  { book: 'Romanos', chapter: 11, verse: 36 },
  { book: 'Romanos', chapter: 12, verse: 1 },
  { book: 'Romanos', chapter: 12, verse: 2 },
  { book: 'Romanos', chapter: 15, verse: 4 },
  { book: 'Romanos', chapter: 15, verse: 13 },

  // ── 1 CORÍNTIOS ──────────────────────────────────────────────────────────────
  { book: '1 Coríntios', chapter: 1, verse: 18 },
  { book: '1 Coríntios', chapter: 1, verse: 23 },
  { book: '1 Coríntios', chapter: 1, verse: 30 },
  { book: '1 Coríntios', chapter: 2, verse: 2 },
  { book: '1 Coríntios', chapter: 2, verse: 9 },
  { book: '1 Coríntios', chapter: 3, verse: 11 },
  { book: '1 Coríntios', chapter: 6, verse: 20 },
  { book: '1 Coríntios', chapter: 10, verse: 13 },
  { book: '1 Coríntios', chapter: 10, verse: 31 },
  { book: '1 Coríntios', chapter: 13, verse: 13 },
  { book: '1 Coríntios', chapter: 15, verse: 3 },
  { book: '1 Coríntios', chapter: 15, verse: 10 },
  { book: '1 Coríntios', chapter: 15, verse: 20 },
  { book: '1 Coríntios', chapter: 15, verse: 55 },
  { book: '1 Coríntios', chapter: 15, verse: 57 },
  { book: '1 Coríntios', chapter: 15, verse: 58 },

  // ── 2 CORÍNTIOS ──────────────────────────────────────────────────────────────
  { book: '2 Coríntios', chapter: 1, verse: 3 },
  { book: '2 Coríntios', chapter: 3, verse: 18 },
  { book: '2 Coríntios', chapter: 4, verse: 6 },
  { book: '2 Coríntios', chapter: 4, verse: 7 },
  { book: '2 Coríntios', chapter: 4, verse: 17 },
  { book: '2 Coríntios', chapter: 5, verse: 7 },
  { book: '2 Coríntios', chapter: 5, verse: 17 },
  { book: '2 Coríntios', chapter: 5, verse: 21 },
  { book: '2 Coríntios', chapter: 9, verse: 8 },
  { book: '2 Coríntios', chapter: 12, verse: 9 },
  { book: '2 Coríntios', chapter: 12, verse: 10 },

  // ── GÁLATAS ──────────────────────────────────────────────────────────────────
  { book: 'Gálatas', chapter: 2, verse: 20 },
  { book: 'Gálatas', chapter: 3, verse: 13 },
  { book: 'Gálatas', chapter: 3, verse: 26 },
  { book: 'Gálatas', chapter: 4, verse: 4 },
  { book: 'Gálatas', chapter: 5, verse: 1 },
  { book: 'Gálatas', chapter: 5, verse: 22 },
  { book: 'Gálatas', chapter: 6, verse: 14 },

  // ── EFÉSIOS ──────────────────────────────────────────────────────────────────
  { book: 'Efésios', chapter: 1, verse: 3 },
  { book: 'Efésios', chapter: 1, verse: 4 },
  { book: 'Efésios', chapter: 1, verse: 7 },
  { book: 'Efésios', chapter: 1, verse: 11 },
  { book: 'Efésios', chapter: 2, verse: 1 },
  { book: 'Efésios', chapter: 2, verse: 4 },
  { book: 'Efésios', chapter: 2, verse: 8 },
  { book: 'Efésios', chapter: 2, verse: 10 },
  { book: 'Efésios', chapter: 3, verse: 20 },
  { book: 'Efésios', chapter: 4, verse: 32 },
  { book: 'Efésios', chapter: 5, verse: 2 },
  { book: 'Efésios', chapter: 6, verse: 10 },
  { book: 'Efésios', chapter: 6, verse: 17 },
  { book: 'Efésios', chapter: 6, verse: 18 },

  // ── FILIPENSES ───────────────────────────────────────────────────────────────
  { book: 'Filipenses', chapter: 1, verse: 6 },
  { book: 'Filipenses', chapter: 2, verse: 5 },
  { book: 'Filipenses', chapter: 2, verse: 13 },
  { book: 'Filipenses', chapter: 3, verse: 8 },
  { book: 'Filipenses', chapter: 3, verse: 14 },
  { book: 'Filipenses', chapter: 4, verse: 4 },
  { book: 'Filipenses', chapter: 4, verse: 6 },
  { book: 'Filipenses', chapter: 4, verse: 7 },
  { book: 'Filipenses', chapter: 4, verse: 13 },
  { book: 'Filipenses', chapter: 4, verse: 19 },

  // ── COLOSSENSES ──────────────────────────────────────────────────────────────
  { book: 'Colossenses', chapter: 1, verse: 15 },
  { book: 'Colossenses', chapter: 1, verse: 17 },
  { book: 'Colossenses', chapter: 1, verse: 18 },
  { book: 'Colossenses', chapter: 1, verse: 27 },
  { book: 'Colossenses', chapter: 2, verse: 3 },
  { book: 'Colossenses', chapter: 2, verse: 9 },
  { book: 'Colossenses', chapter: 2, verse: 13 },
  { book: 'Colossenses', chapter: 3, verse: 1 },
  { book: 'Colossenses', chapter: 3, verse: 16 },
  { book: 'Colossenses', chapter: 3, verse: 17 },

  // ── 1 TESSALONICENSES ────────────────────────────────────────────────────────
  { book: '1 Tessalonicenses', chapter: 4, verse: 16 },
  { book: '1 Tessalonicenses', chapter: 5, verse: 16 },
  { book: '1 Tessalonicenses', chapter: 5, verse: 17 },
  { book: '1 Tessalonicenses', chapter: 5, verse: 18 },
  { book: '1 Tessalonicenses', chapter: 5, verse: 23 },

  // ── 2 TESSALONICENSES ────────────────────────────────────────────────────────
  { book: '2 Tessalonicenses', chapter: 2, verse: 13 },
  { book: '2 Tessalonicenses', chapter: 3, verse: 3 },

  // ── 1 TIMÓTEO ────────────────────────────────────────────────────────────────
  { book: '1 Timóteo', chapter: 1, verse: 15 },
  { book: '1 Timóteo', chapter: 2, verse: 5 },
  { book: '1 Timóteo', chapter: 3, verse: 16 },
  { book: '1 Timóteo', chapter: 6, verse: 6 },
  { book: '1 Timóteo', chapter: 6, verse: 12 },

  // ── 2 TIMÓTEO ────────────────────────────────────────────────────────────────
  { book: '2 Timóteo', chapter: 1, verse: 7 },
  { book: '2 Timóteo', chapter: 1, verse: 9 },
  { book: '2 Timóteo', chapter: 2, verse: 15 },
  { book: '2 Timóteo', chapter: 3, verse: 16 },
  { book: '2 Timóteo', chapter: 4, verse: 7 },

  // ── TITO ─────────────────────────────────────────────────────────────────────
  { book: 'Tito', chapter: 2, verse: 11 },
  { book: 'Tito', chapter: 3, verse: 4 },
  { book: 'Tito', chapter: 3, verse: 7 },

  // ── HEBREUS ──────────────────────────────────────────────────────────────────
  { book: 'Hebreus', chapter: 1, verse: 1 },
  { book: 'Hebreus', chapter: 1, verse: 3 },
  { book: 'Hebreus', chapter: 2, verse: 17 },
  { book: 'Hebreus', chapter: 4, verse: 12 },
  { book: 'Hebreus', chapter: 4, verse: 14 },
  { book: 'Hebreus', chapter: 4, verse: 16 },
  { book: 'Hebreus', chapter: 7, verse: 25 },
  { book: 'Hebreus', chapter: 9, verse: 14 },
  { book: 'Hebreus', chapter: 10, verse: 14 },
  { book: 'Hebreus', chapter: 10, verse: 23 },
  { book: 'Hebreus', chapter: 11, verse: 1 },
  { book: 'Hebreus', chapter: 11, verse: 6 },
  { book: 'Hebreus', chapter: 12, verse: 1 },
  { book: 'Hebreus', chapter: 12, verse: 2 },
  { book: 'Hebreus', chapter: 12, verse: 6 },
  { book: 'Hebreus', chapter: 13, verse: 5 },
  { book: 'Hebreus', chapter: 13, verse: 8 },

  // ── TIAGO ────────────────────────────────────────────────────────────────────
  { book: 'Tiago', chapter: 1, verse: 2 },
  { book: 'Tiago', chapter: 1, verse: 5 },
  { book: 'Tiago', chapter: 1, verse: 12 },
  { book: 'Tiago', chapter: 1, verse: 17 },
  { book: 'Tiago', chapter: 4, verse: 7 },
  { book: 'Tiago', chapter: 5, verse: 16 },

  // ── 1 PEDRO ──────────────────────────────────────────────────────────────────
  { book: '1 Pedro', chapter: 1, verse: 3 },
  { book: '1 Pedro', chapter: 1, verse: 5 },
  { book: '1 Pedro', chapter: 1, verse: 15 },
  { book: '1 Pedro', chapter: 1, verse: 18 },
  { book: '1 Pedro', chapter: 2, verse: 9 },
  { book: '1 Pedro', chapter: 2, verse: 24 },
  { book: '1 Pedro', chapter: 3, verse: 15 },
  { book: '1 Pedro', chapter: 5, verse: 6 },
  { book: '1 Pedro', chapter: 5, verse: 7 },
  { book: '1 Pedro', chapter: 5, verse: 8 },

  // ── 2 PEDRO ──────────────────────────────────────────────────────────────────
  { book: '2 Pedro', chapter: 1, verse: 3 },
  { book: '2 Pedro', chapter: 1, verse: 10 },
  { book: '2 Pedro', chapter: 3, verse: 9 },
  { book: '2 Pedro', chapter: 3, verse: 18 },

  // ── 1 JOÃO ───────────────────────────────────────────────────────────────────
  { book: '1 João', chapter: 1, verse: 7 },
  { book: '1 João', chapter: 1, verse: 9 },
  { book: '1 João', chapter: 2, verse: 1 },
  { book: '1 João', chapter: 3, verse: 1 },
  { book: '1 João', chapter: 3, verse: 16 },
  { book: '1 João', chapter: 4, verse: 4 },
  { book: '1 João', chapter: 4, verse: 8 },
  { book: '1 João', chapter: 4, verse: 10 },
  { book: '1 João', chapter: 4, verse: 18 },
  { book: '1 João', chapter: 4, verse: 19 },
  { book: '1 João', chapter: 5, verse: 4 },
  { book: '1 João', chapter: 5, verse: 11 },
  { book: '1 João', chapter: 5, verse: 20 },

  // ── APOCALIPSE ───────────────────────────────────────────────────────────────
  { book: 'Apocalipse', chapter: 1, verse: 5 },
  { book: 'Apocalipse', chapter: 1, verse: 8 },
  { book: 'Apocalipse', chapter: 2, verse: 10 },
  { book: 'Apocalipse', chapter: 3, verse: 20 },
  { book: 'Apocalipse', chapter: 4, verse: 8 },
  { book: 'Apocalipse', chapter: 4, verse: 11 },
  { book: 'Apocalipse', chapter: 5, verse: 9 },
  { book: 'Apocalipse', chapter: 5, verse: 12 },
  { book: 'Apocalipse', chapter: 11, verse: 15 },
  { book: 'Apocalipse', chapter: 12, verse: 11 },
  { book: 'Apocalipse', chapter: 19, verse: 6 },
  { book: 'Apocalipse', chapter: 21, verse: 4 },
  { book: 'Apocalipse', chapter: 21, verse: 5 },
  { book: 'Apocalipse', chapter: 22, verse: 12 },
  { book: 'Apocalipse', chapter: 22, verse: 20 },
];
